export const GLOBALTYPES = {
    AUTH: "AUTH",
    NOTIFY: "NOTIFY",
    ALERT: "ALERT",
    LOADING_PROFILE: "LOADING_PROFILE",
    GET_USER: "GET_USER",
    STATUS: 'STATUS',
    CREATE_POST: 'CREATE_POST',
    LOADING_POST: 'LOADING_POST',
    GET_POSTS: 'GET_POSTS',
    UPDATE_POST: 'UPDATE_POST'
}